updated logging output and added exit 1 in case of failure to indicate that something did go wrong.

diff --git a/stemcell_builder/stages/bosh_go_agent/assets/02-restrict-nats-api-access-allow-monit-api b/stemcell_builder/stages/bosh_go_agent/assets/02-restrict-nats-api-access-allow-monit-api
--- a/stemcell_builder/stages/bosh_go_agent/assets/02-restrict-nats-api-access-allow-monit-api
+++ b/stemcell_builder/stages/bosh_go_agent/assets/02-restrict-nats-api-access-allow-monit-api
@@ -46,7 +46,8 @@ wait_for_agent_settings() {
                  -m cgroup \! --cgroup "${nats_isolation_classid}" -j DROP
       fi
     else
-      echo "no nats protocol connection found. assuming create-env"
+      echo "Nats Address couldn't be parsed into IP:PORT, this script is failing to interpret the /var/vcap/bosh/settings.json"
+      exit 1
     fi
   fi
 }
